const STATUS_CODES = Object.freeze({
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    KEY_NOT_FOUND: 'KEY_NOT_FOUND',
    INVALID_PARAMETER: 'INVALID_PARAMETER',
});

module.exports = STATUS_CODES;