const STATUS_CODES = Object.freeze({
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    FILE_NOT_FOUND: 'FILE_NOT_FOUND',
    FILE_ALREADY_EXISTS: 'FILE_ALREADY_EXISTS',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    FILE_TYPE_NOT_SUPPORTED: 'FILE_TYPE_NOT_SUPPORTED',
    FILE_WRITE_ERROR: 'FILE_WRITE',
    FILE_CURRUPTED: 'FILE_CURRUPTED',
    INVALID_PARAMETER: 'INVALID_PARAMETER',
});

module.exports = STATUS_CODES;