const STATUS_CODES = Object.freeze({
    SUCCESS: 'SUCCESS',
    DB_NOT_EXIST: 'DB_NOT_EXIST',
    DB_ALREADY_EXISTS: 'DB_ALREADY_EXISTS',
    DB_CORRUPTED: 'DB_CORRUPTED',
    KEY_NOT_FOUND: 'KEY_NOT_FOUND',
    KEY_EXISTS: 'KEY_EXISTS',
    INVALID_KEY_PATH: 'INVALID_KEY_PATH',
    INVALID_VALUE: 'INVALID_VALUE',
    INVALID_PARAMETER: 'INVALID_PARAMETER',
});

module.exports = STATUS_CODES;